apiVersion: v1
kind: Service
metadata:
  name: medfast-frontend
  labels:
    owner: RamanMarkau
spec:
  selector:
    app: {{ .Release.Name }}-medfast-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
