apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-medfast-backend
  annotations:
    iam.gke.io/gcp-service-account: gke-quickstart-service-account@velvety-gearbox-439710-c9.iam.gserviceaccount.com
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-medfast-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-medfast-backend
    spec:
      serviceAccountName: ksa-cloud-sql
      containers:
      - name: {{ .Release.Name }}-medfast-backend
        image: {{ .Values.container.image }}
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: SPRING_DATASOURCE_PASSWORD 
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: backend-config 
              key: SPRING_PROFILES_ACTIVE 
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
      
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
        args:
          - "--auto-iam-authn"
          - "--port=5432"
          - "velvety-gearbox-439710-c9:us-central1:quickstart-instance"
        resources:
          requests:
            memory: "128Mi"  
            cpu: "100m"      
          limits:
            memory: "256Mi"  
            cpu: "500m"      
        securityContext:
          runAsNonRoot: true
