apiVersion: v1
kind: Service
metadata:
  name: medfast-backend
  labels:
    owner: RamanMarkau
spec:
  selector:
    app: {{ .Release.Name }}-medfast-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  
